Feature/heroes
Rise-in-Time/rise-in-time-orb pull request #55
Opened 2021-07-09 15:01 UTC by MrMichael3

added hero article
small adjustments

2021-07-14 17:01 UTC, ArminWindlin requested changes
Nice addition.

Maybe we can use the same images for the heroes we currently use ingame. I can send them to you if they are not in the wiki yet?

2021-07-14 17:01 UTC, ArminWindlin commented on src/views/article.vue
> +                                console.log("change recSpeed")
remove console.log

2021-07-17 07:54 UTC, MrMichael3 commented on src/views/article.vue
> +                                console.log("change recSpeed")
done

2021-07-18 09:46 UTC, ArminWindlin approved these changes

2021-07-18 10:19 UTC, merged